export default [
    // Regex returns 3 groups
    // Group 1: Class, e.g. "Cleric"
    // Group 2: additional words, e.g. "of Nethys"
    // Group 3: Level, e.g. "9"
    "Adept \\d+",
    "Alchemist \\d+",
    "Antipaladin \\d+",
    "Arcanist \\d+",
    "Aristocrat \\d",
    "Barbarian \\d+",
    "Bard \\d+",
    "Bloodrager \\d+",
    "Brawler \\d+",
    "Cavalier \\d+",
    "(Cleric)(?:[\s]*?)([\w\s]*?)(?:[\s]*?)(\d+)",
    "Commoner \\d",
    "Druid \\d+",
    "Expert \\d",
    "Fighter \\d+",
    "Gunslinger \\d+",
    "Hunter \\d+",
    "Inquisitor \\d+",
    "Investigator \\d+",
    "Kineticist \\d+",
    "Magus \\d+",
    "Medium \\d+",
    "Mesmerist \\d+",
    "Monk \\d+",
    "Ninja \\d+",
    "Omdura \\d+",
    "Occultist \\d+",
    "Oracle \\d+",
    "Paladin \\d+",
    "Psychic \\d+",
    "Ranger \\d+",
    "Rogue \\d+",
    "Samurai \\d+",
    "Shaman \\d+",
    "Shifter \\d+",
    "Skald \\d+",
    "Slayer \\d+",
    "Sorcerer \\d+",
    "Spiritualist \\d+",
    "Summoner \\d+",
    "Swashbuckler \\d+",
    "Vampire Hunter \\d+",
    "Vigilante \\d+",
    "Warpriest \\d+",
    "Warrior \\d",
    "Witch \\d+",
    "Wizard \\d+"    
];