export default {
    "name": "",
    "classes": {},
    "slug": "",
    "flavor_text": "",
    "cr": 0,
    "xp": 0,
    "size": "",
    "alignment": "",
    "gender": "",
    "race": "",
    "creature_type": "",
    "creature_subtype": "",
    "initiative": 0,
    "senses": "",
    "aura": "",
    "hp": {
        "total": 0,
        "racial": 0,
        "class": 0
    },
    "hit_dice" : {
        "hd": 0,
        "hd_diceSize": 0,
        "hd_bonus": 0
    },
    "ac": 0,
    "touch": 0,
    "flat_footed" : 0,
    "ac_bonus_types" : {},
    "fort_save": 0,
    "ref_save": 0,
    "will_save": 0,
    "defensive_abilities": "",
    "immunities": "",
    "resistances": "",
    "weaknesses": "",
    "spell_resistance": 0,
    "damage_reduction": {
        "dr_value" : 0,
        "dr_type" : ""
    },
    "regeneration": "",
    "fast_healing": "",
    "speed": 0,
    "melee": "",
    "ranged": "",
    "space": 0,
    "reach": 0,
    "offensive_abilities": "",
    "spell_like_abilities": "",
    "str": 0,
    "dex": 0,
    "con": 0,
    "int": 0,
    "wis": 0,
    "cha": 0,
    "feats": [],
    "skills": {
        "acrobatics" : 0,
        "appraise" : 0,
        "bluff" : 0,
        "climb" : 0,
        "craft" : {},
        "diplomacy" : 0,
        "disableDevice" : 0,
        "disguise" : 0,
        "escapeArtist" : 0,
        "fly" : 0,
        "handleAnimal" : 0,
        "heal" : 0,
        "intimidate" : 0,
        "knowledge" : {
            "arcana" : 0,
            "dungeoneering" : 0,
            "engineering" : 0,
            "geography" : 0,
            "history" : 0,
            "local" : 0,
            "nature" : 0,
            "nobility" : 0,
            "planes" : 0,
            "religion" : 0
        },
        "linguistics" : 0,
        "perception" : 0,
        "perform" : {},
        "profession" : {},
        "ride" : 0,
        "senseMotive" : 0,
        "sleightOfHand" : 0,
        "spellcraft" : 0,
        "stealth" : 0,
        "survival" : 0,
        "swim" : 0,
        "useMagicDevice" : 0
    },
    "tactics": {
        "before_combat" : "",
        "during_combat" : "",
        "morale" : "",
        "base_statistics" : "",
        "default" : ""
    },
    "languages": "",
    "gear": "",
    "other_abilities": "",
    "environment": "",
    "organization": "",
    "special_abilities": "",
    "description": ""
};